### ISSUE TITLE
set-map-view

### ISSUE THREAD

**Issue by Brian393** [Brian393/ecotopia-today#8]
@edwardsharp

The set-map-view method works perfectly on WatershedIntroduction and WatershedHanfordLegacy, but when I try to use it on WatershedFalls it does not work.

I realize I am supposed to place " import {eventBus} from '../../main' " at the end of the template, but when I do the application freezes. I have tried exactly copying the working code from the other pages, but no luck.

**Comment by edwardsharp** [comment]
hmm, not at the end of the template but at the top of the `<script>` section. so yes, the reason it's not working now is because you haven't imported the `eventBus` object. see: https://github.com/Brian393/ecotopia-today/blob/master/src/views/watershed/WatershedFalls.vue

but i'm confused, because you _used to_ have the import, see: https://github.com/Brian393/ecotopia-today/blob/43d68da0ac3554722b2bd1ba9ba1858fbb789a50/src/views/watershed/WatershedFalls.vue#L83 

🤔 why did you take it out? just add it back and it should work like you want it to work. 👍

**Comment by Brian393** [comment]
Well, I tried putting the eventBus object in and the whole application
freezes, as I said in the issue. I also tried copying and pasting the bits
from the templates where it works, into this template - and it still
freezes. So there is a conflict somewhere.. I have probably spent four
hours trying every possible thing, several times, making sure the code is
right, etc. And the strangest thing is, it does work in the other
templates. But even when I copy-paste the working code into this template,
it does not work.

In the earlier commit that you reference, both the import line and the two
method lines are there, but the method is not deployed in the template
itself. So the problem doesn't appear.

Probably it's best that you test it. There is definitely a problem, and it
could well be something silly that I have done, but it is not just putting
the eventbus object back in that will resolve it.
